#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=16,pmem=3500mb
#PBS -m abe
#PBS -M tasta005@umn.edu
#PBS -N bam_star_align
#PBS -o logs/output
#PBS -e logs/error

module load gcc star

cd ~/ocpmi/data/bam/wes1/tmp

## For looped, compressed
for i in *_R1_001.fastq.gz; do
STAR --runMode alignReads \
    --outSAMtype BAM SortedByCoordinate \
    --readFilesIn $i ${i%_R1_001.fastq.gz}_R2_001.fastq.gz \
    --readFilesCommand zcat \
    --genomeDir ~/ocpmi/data/gene_ref/ucsc/hg38 \
#   --genomeLoad LoadAndRemove \
#   --limitBAMsortRAM 56000000000 \
    --runThreadN 16 \
    --outFileNamePrefix ${i%_R1_001.fastq.gz}_
done

### Individual files
#STAR --runMode alignReads \
#    --outSAMtype BAM SortedByCoordinate \
#    --genomeDir ~/ocpmi/data/gene_ref/ucsc/hg38 \
#    --readFilesIn read_1.fastq.gz read_2.fastq.gz \
#    --runThreadN 8 \
#    --outFileNamePrefix NA10847_SRR070823
