#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=16,mem=32gb
#PBS -m abe
#PBS -M tasta005@umn.edu
#PBS -N bam_star_align
#PBS -o logs/output
#PBS -e logs/error

module load gcc star

cd ~/ocpmi/data/bam/wes1

## For looped
for i in *_R1_001.fastq.gz; do
STAR --runMode alignReads \
    --outSAMtype BAM SortedByCoordinate \
    --readFilesCommand zcat \
    --genomeDir ~/ocpmi/data/gene_ref/ucsc/hg38 \
    --readFilesIn $i ${i%_R1_001.fastq.gz}_R2_001.fastq.gz \
    --runThreadN 16 \
    --outFileNamePrefix ${i%_R1_001.fastq.gz}_
done

### Individual files
#STAR --runMode alignReads \
#    --outSAMtype BAM SortedByCoordinate \
#    --genomeDir ~/ocpmi/data/gene_ref/ucsc/hg38 \
#    --readFilesIn read_1.fastq.gz read_2.fastq.gz \
#    --runThreadN 8 \
#    --outFileNamePrefix NA10847_SRR070823
