---
title: "Seurat Analysis - Pt59"
author: "Christopher Tastad"
date: \today
bibliography: library.bib
output:
    html_document:
        df_print: kable
        toc: yes
        toc_float: yes
        theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
```

# Dependencies, Initialize

```{r}
library(dplyr)
library(Seurat)

setwd("~/starr_lab/ocpmi/code/")
pt59.data <- Read10X(data.dir = "/home/chris/starr_lab/ocpmi/code/pt59/")
pt59 <- CreateSeuratObject(counts = pt59.data, project = "pt59", min.cells = 3, min.features = 200)
pt59
```

# Survey data

```{r eval=F}
pt59.data[c("CD3D","TCL1A","MS4A1"), 1:30]
dense.size <- object.size(x = as.matrix(x = pt59.data))
dense.size
```

# Pre-processing workflow

```{r}
pt59[["percent.mt"]] <- PercentageFeatureSet(object = pt59, pattern = "^MT-")
```

## Visualize QC metrics

```{r}
VlnPlot(object = pt59, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```


