#!/bin/bash -l
#PBS -l walltime=8:00:00,nodes=1:ppn=8,mem=16gb
#PBS -m abe
#PBS -M tasta005@umn.edu
#PBS -N bam_create
#PBS -o logs/output
#PBS -e logs/error

cd ~/ocpmi/bam
module load bwa
module load samtools
bwa mem -t 8 ~/ocpmi/gene_ref/hg38.fa PM-15-T17-0910-1_S2_R1_001.fastq | samtools sort -@8 -o pm15.bam -
bwa mem -t 8 ~/ocpmi/gene_ref/hg38.fa PM-2-T17-0307-3_S9_R1_001.fastq | samtools sort -@8 -o pm2.bam -
