#!/bin/bash -l
#PBS -l walltime=8:00:00,nodes=1:ppn=8,mem=16gb
#PBS -m abe
#PBS -M tasta005@umn.edu
#PBS -N excv2_dataprep
#PBS -o logs/output
#PBS -e logs/error

cd ~/ocpmi/methods/EXCAVATOR2_Package_v1.1.2
module load R
module load perl
module load intel
module load bedtools
module load samtools
perl EXCAVATORDataPrepare.pl ExperimentalFilePrepare.50000.txt --processors 8 --target test_target_38 --assembly hg38
