#!/bin/bash -l
#PBS -l walltime=8:00:00,nodes=1:ppn=8,mem=16gb
#PBS -m abe
#PBS -M tasta005@umn.edu
#PBS -N excv2_data_an
#PBS -o logs/output
#PBS -e logs/error

module load R
module load perl
module load intel
module load bedtools
module load samtools
cd ~/ocpmi/methods/EXCAVATOR2_Package_v1.1.2
perl EXCAVATORDataAnalysis.pl ExperimentalFileAnalysis.50000.txt --processors 8 --target test_target_38 --assembly hg38 --output ~/ocpmi/methods/EXCAVATOR2_Package_v1.1.2/data/output/analysis --mode pooling
