---
title: "Gene Association Table"
author: "Christopher Tastad"
date: "Last Edit: `r format(Sys.time(), '%Y-%m-%d')`"
output:
    html_document:
        theme: paper
---

```{r}
library(knitr)
library(DT)
library(reshape2)
```

```{r}
geneAssociationTable <- read.table("geneAssociationTable",
                                   header = F,
                                   sep = "\t")
colnames(geneAssociationTable) <- c("seqId", "geneName", "call", "sampleId")
tableWide_lab <- dcast(geneAssociationTable,
                   seqId + geneName ~ sampleId,
                   value.var = "call",
                   fun = median,
                   fill = 0)

names(tableWide_lab) <- substring(names(tableWide_lab), 4, 9)
colnames(tableWide_lab)[1:3] <- c("seqId", "geneName", "NA10847")

DT::datatable(tableWide_lab) %>%
    formatStyle(names(tableWide_lab),
                backgroundColor = styleEqual(
                                             c(-2, -1, 0, 1, 2),
                                             c('blue', 'lightblue', 'white', 'pink', 'red')))

# DT::datatable(tableWide_lab)
```
